import type { Project } from '../types/project'

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Operation Glasshouse',
    caseRef: 'NFIB-2026-0441',
    classification: 'OFFICIAL-SENSITIVE',
    investigationType: 'Fraud / Financial crime',
    status: 'active',
    riskLevel: 'HIGH',
    nodeCount: 18,
    edgeCount: 20,
    entityCounts: { ip: 3, domain: 5, email: 3, person: 4, org: 2, wallet: 1 },
    analystInitials: 'JA',
    analystName: 'J. Ali',
    createdAt: '2026-05-14T09:00:00Z',
    updatedAt: '2026-06-07T10:22:00Z',
    lastAction: 'Enriched domain malicious-update[.]net via Shodan',
  },
  {
    id: 'p2',
    name: 'APP Fraud — Ref 2026/4421',
    caseRef: 'URN-2026-4421',
    classification: 'OFFICIAL',
    investigationType: 'Fraud / Financial crime',
    status: 'active',
    riskLevel: 'MEDIUM',
    nodeCount: 14,
    edgeCount: 16,
    entityCounts: { person: 4, org: 2, ip: 4, email: 3, wallet: 1 },
    analystInitials: 'JA',
    analystName: 'J. Ali',
    createdAt: '2026-05-28T14:30:00Z',
    updatedAt: '2026-06-06T16:45:00Z',
    lastAction: 'Added 3 mule accounts from CSV import',
  },
  {
    id: 'p3',
    name: 'Cobalt Strike C2 Cluster',
    classification: 'OFFICIAL-SENSITIVE',
    investigationType: 'Cyber / Infrastructure',
    status: 'active',
    riskLevel: 'HIGH',
    nodeCount: 16,
    edgeCount: 21,
    entityCounts: { ip: 8, domain: 6, org: 2 },
    analystInitials: 'JA',
    analystName: 'J. Ali',
    createdAt: '2026-04-03T08:15:00Z',
    updatedAt: '2026-06-04T11:20:00Z',
    lastAction: 'Exported STIX 2.1 bundle to NCSC sharing portal',
  },
  {
    id: 'p4',
    name: 'Romance Fraud Network',
    caseRef: 'NFIB-2026-0389',
    classification: 'OFFICIAL',
    investigationType: 'Fraud / Financial crime',
    status: 'paused',
    riskLevel: 'MEDIUM',
    nodeCount: 11,
    edgeCount: 14,
    entityCounts: { person: 5, email: 3, phone: 2, org: 1 },
    analystInitials: 'JA',
    analystName: 'J. Ali',
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-30T09:10:00Z',
    lastAction: 'Intelligence graded — source B2',
  },
  {
    id: 'p5',
    name: 'Phishing Kit — HMRC Spoof',
    caseRef: 'AF-2026-7821',
    classification: 'OFFICIAL',
    investigationType: 'Cyber / Infrastructure',
    status: 'active',
    riskLevel: 'HIGH',
    nodeCount: 14,
    edgeCount: 17,
    entityCounts: { domain: 6, ip: 4, email: 3, url: 1 },
    analystInitials: 'JA',
    analystName: 'J. Ali',
    createdAt: '2026-06-01T13:00:00Z',
    updatedAt: '2026-06-07T08:55:00Z',
    lastAction: 'Flagged 2 domains for takedown referral',
  },
]
